[package]
name = "registry"
version = "1.0.0"
authors = ["Keith Amling <me@amling2.org>"]

[dependencies]
opts = { path = "../opts" }
registry_args = { path = "../registry_args" }
registry_args_derive = { path = "../registry_args_derive" }
validates = { path = "../validates" }
