[package]
name = "r4"
version = "1.0.0"
authors = ["Keith Amling <me@amling2.org>"]

[dependencies]
operation = { path = "../operation" }
stream = { path = "../stream" }
stream_process = { path = "../stream_process" }
stream_stdout = { path = "../stream_stdout" }
