[package]
name = "deaggregator"
version = "1.0.0"
authors = ["Keith Amling <me@amling2.org>"]
edition = "2018"

[dependencies]
record = { path = "../record" }
registry = { path = "../registry" }
lazy_static = "1.2.0"
