[package]
name = "operation"
version = "1.0.0"
authors = ["Keith Amling <me@amling2.org>"]

[dependencies]
bgop = { path = "../bgop" }
opts = { path = "../opts" }
record = { path = "../record" }
registry = { path = "../registry" }
stream = { path = "../stream" }
serde_json = "1.0"
