[package]
name = "sorts"
version = "1.0.0"
authors = ["Keith Amling <me@amling2.org>"]

[dependencies]
record = { path = "../record" }
registry = { path = "../registry" }
registry_args = { path = "../registry_args" }
lazy_static = "1.2.0"
rand = "0.6.1"
rand_chacha = "0.1.0"
