[package]
name = "aggregator"
version = "1.0.0"
authors = ["Keith Amling <me@amling2.org>"]

[dependencies]
misc = { path = "../misc" }
record = { path = "../record" }
registry = { path = "../registry" }
validates = { path = "../validates" }
lazy_static = "1.2.0"
