[package]
name = "registry_args_derive"
version = "1.0.0"
authors = ["Keith Amling <me@amling2.org>"]

[lib]
proc-macro = true

[dependencies]
"proc-macro2" = "0.4.21"
"quote" = "0.6"

[dependencies.syn]
version = "0.15.23"
features = ["extra-traits"]
