[package]
name = "clumper"
version = "1.0.0"
authors = ["Keith Amling <me@amling2.org>"]

[dependencies]
record = { path = "../record" }
registry = { path = "../registry" }
stream = { path = "../stream" }
lazy_static = "1.2.0"
